export enum LawService {
  IDP_REGISTRATION = 'IDP registration',
  SOCIAL_WELFARE = 'Social welfare',
  PENSION_RECOVERY = 'Pension recovery',
  CIVIL_DOCUMENTATION = 'Civil documentation',
  HLP = 'HLP',
  RULES_FOR_MOVING_ABROAD = 'Rules for moving abroad',
  TP_REFUGEE_ASYLUM = 'TP,Refugee,Asylum',
  MOVING_WITHIN_EU = 'Moving within EU',
  OBTAINING_CITIZENSHIP = 'Obtaining citizenship or a permanent residence permit',
  EXEMPTION_FROM_CONSCRIPTION = 'Exemption from conscription',
  EMPLOYMENT_RELATED = 'Employment related',
  FAMILY_INC_REUNIFICATION = 'Family inc. reunification',
  CHILD_RIGHTS = 'Child rights',
  EDUCATION = 'Education',
  HEALTH = 'Health',
  DIGITAL_SERVICE = 'Digital service inc. Diia',
  CREDITS_LOANS = 'Credits-Loans',
  BUSINESS_ISSUES = 'Business issues',
  UXO = 'UXO',
}
