export enum PlaceOfResidence {
  VINNYTSKA = 'Vinnytska',
  VOLYNSKA = 'Volynska',
  DNIPROPETROVSKA = 'Dnipropetrovska',
  JYTOMYRSKA = 'Jytomyrska',
  DONETSKA = 'Donetska',
  ZAKARPATSKA = 'Zakarpatska',
  ZAPORIZKA = 'Zaporizka',
  IVANO_FRANKIVSKA = 'Ivano-Frankivska',
  KYIVSKA = 'Kyivska',
  KIROVOGRADSKA = 'Kirovogradska',
  LUGANSKA = 'Luganska',
  LVIVSKA = 'Lvivska',
  MYKOLAIVSKA = 'Mykolaivska',
  ODESKA = 'Odeska',
  POLTAVSKA = 'Poltavska',
  RIVNENSKA = 'Rivnenska',
  SUMSKA = 'Sumska',
  TERNOPILSKA = 'Ternopilska',
  KHARKIVSKA = 'Kharkivska',
  KHERSONSKA = 'Khersonska',
  KHMELNITSKA = 'Kmelnitska',
  CHERKASKA = 'Cherkaska',
  CHERNIHIVSKA = 'Chernihivska',
  CHERNIVETSKA = 'Chernivetska',
}
