export enum Specializations {
  InternallyDisplacedPersons = 'internallyDisplacedPersons',
  SocialWelfarePrograms = 'socialWelfarePrograms',
  Pension = 'pension',
  EmploymentIssues = 'employmentIssues',
  RegistrationOfBirth = 'registrationOfBirth',
  RegistrationOfDeath = 'registrationOfDeath',
  Diia = 'diia',
  MissingPerson = 'missingPerson',
  AccessToHealthcare = 'accessToHealthcare',
  AccessToEducation = 'accessToEducation',
  FamilyRelations = 'familyRelations',
  ChildrenAndMinors = 'childrenAndMinors',
  GoingAbroad = 'goingAbroad',
  RulesForPetOwners = 'rulesForPetOwners',
  HLP = 'hlp',
  CompensationForProperty = 'compensationForProperty',
  MortgageAndLoanIssues = 'mortgageAndLoanIssues',
  WillsAndInheritance = 'willsAndInheritance',
  Conscription = 'conscription',
  VeteransRightsAndGuarantees = 'veteransRightsAndGuarantees',
  Entrepreneurship = 'entrepreneurship',
  RegulationOfVolunteerActivities = 'regulationOfVolunteerActivities',
  Citizenship = 'citizenship',
  ReefugeesProtection = 'reefugeesProtection',
  RecoveryPersonalDocumentation = 'recoveryPersonalDocumentation',
  DrivingLicenseAndRegistration = 'drivingLicenseAndRegistration',
}
