export enum NotificationTypes {
  admin_NEW_ADMIN_REGISTERED = 'New admin registered',
  admin_NEW_MODERATOR_REGISTERED = 'New moderator registered',
  customer_LAWYER_SENT_MESSAGE = 'Lawyer sent message',
  customer_LAWYER_REJECT_CONSULTATION = 'Lawyer rejected consultation',
  customer_LAWYER_RESCHEDULRE_CONSULTATION = 'Lawyer reschedule consultation',
  customer_PROVIDE_CONSULTATION_FEEDBACK = 'Provide the consultation feedback (in 24 hours push)',
  customer_LAWYER_APPROVED_TIME_FOR_CONSULTATION = 'Lawyer approved time for consultation',
  customer_LAWYER_ADDED_LINK = 'Lawyer added the link',
  lawyer_CUSTOMER_SENT_MESSAGE = 'Customer sent message',
  lawyer_CUSTOMER_SCHEDULED_CONSULTATION = 'Customer scheduled consultation',
  lawyer_CUSTOMER_REJECTED_CONSULTATION = 'Customer rejected consultation',
  lawyer_CUSTOMER_RESCHEDULE_CONSULTATION = 'Customer reschedule consultation',
  lawyer_CUSTOMER_APPROVED_NEW_TIME_FOR_CONSULTATION = 'Customer approved new time for consultation',
  lawyer_CUSTOMER_ADDED_FEEDBACK = 'Customer added feedback',
  lawyer_CUSTOMER_ADDED_THE_link = 'Customer added the link',
  lawyer_CUSTOMER_MARKED_CONSULTATION_AS_COMPLETED = 'Customer marked consultation as Completed',
  lawyer_MODERATOR_SENT_THE_MESSAGE = 'Moderator sent the message',
  lawyer_MODERATOR_APPROVED_YOUR_POST = 'Moderator approved your post',
  lawyer_MODERATOR_REJECTED_YOUR_POST = 'Moderator rejected your post',
  lawyer_MODERATOR_APPROVED_YOUR_CHANGES = 'Moderator approved your changes',
  lawyer_MODERATOR_REJECTED_YOUR_CHANGES = 'Moderator rejected your changes',
  moderator_USER_MESSAGED_IN_GENERAL_CHAT = 'User messaged in general chat',
  moderator_LAWYER_SENT_MESSAGE = '(Moderator) Lawyer sent message',
  moderator_LAWYER_SENT_REQUEST_FOR_POST_PUBLISHING = 'Lawyer sent request for post publishing',
  moderator_LAWYER_SENT_REQUEST_FOR_CHANGING_INFORMATION = 'Lawyer sent request for changing information',
}
